Django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('', include('monApp.urls'))

]

monApp/urls.py
from django.urls import path
from monApp import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', views.home),
    path('change_password', views.change_password),
    path('deco', views.deco),
    path('accueil', views.forum, name='forum'),
    path('accueil/langue/<int:langue_id>', views.redirect_langue),
    path('accueil/article/<int:article_id>', views.redirect_article),
    path('accueil/article', views.article, name="article"),
    path('admin', views.admin, name="admin"),
    path('admin/<str:model>/<str:action>', views.admin, name="admin"),
    path('admin/<str:model>/<str:action>/<int:arg>', views.admin, name="admin"),
    path('admin/test', views.test),
    path('admin/excel_import', views.user_import, name="user_import"),
    path('admin/user/<int:arg>/newPassword', views.newPassword, name="newPassword"),
    path('admin/exam_extract', views.examExtract, name="examExtract"),
    path('exam_confirm/<str:arg>', views.test_exam_confirm),
    path('exam_confirm/<str:arg>/confirm', views.exam_confirm_confirm, name="examConfirmConfirm")


]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

monApp/models.py
from django.db import models
from django.utils import timezone
from os import listdir
from datetime import datetime, timedelta
from monApp import util
from django.template.loader import get_template
from django.core.mail import EmailMultiAlternatives
from django.utils import timezone
import json
from colour import Color
from docx import Document


# Create your models here.
class ArticleType(models.Model):
    nom = models.CharField(max_length=50, null=True)
    img = models.ImageField(upload_to="static/img/article_icon", null=True)



class ForumGroup(models.Model):

    def __str__(self):
        return self.nom

    nom = models.CharField(max_length=30)
    couleur = models.CharField(max_length=10)
    logo = models.ForeignKey("logo", on_delete=models.SET_NULL, null=True)
    mail = models.EmailField(null=True, max_length=50)

    list_template = "monApp/admin_group_list.html"
    form_template = "monApp/admin_group_form.html"
    form_fields = ("nom", "couleur", "logo")


    @staticmethod
    def objectList(arg):
        return ForumGroup.objects.all()

    def couleur2(self):
        try:
            c2 = Color(self.couleur)
        except ValueError:
            return "#ffffff"
        l = c2.get_luminance()
        l = (l+1)/2
        c2.set_luminance(l)
        return c2.get_hex()



class LangueSection(models.Model):
    nom_complet = models.CharField(max_length=50)
    nom_apparent = models.CharField(max_length=50)
    groupes = models.ManyToManyField(ForumGroup)

    list_template = "monApp/admin_section_list.html"
    form_template = "monApp/admin_section_form.html"

    def __str__(self):
        return self.nom_complet

    def getArticles(self):
        return Article.objects.filter(langue=self, date__lte=timezone.localdate())

    @staticmethod
    def objectList(arg):
        return LangueSection.objects.all()


class ForumUser(models.Model):
    identifiant = models.CharField(max_length=50, unique=True, null=False)
    password = models.CharField(max_length=300, null=False)
    mail = models.EmailField(null = True)
    groupe = models.ManyToManyField(ForumGroup)
    admin = models.BooleanField(default=False)

    list_template = "monApp/admin_user_list.html"
    form_template = "monApp/admin_user_form.html"

    def __str__(self):
        return self.identifiant


    def getLangues(self):
        langues = []
        for groupe in self.groupe.all():
            langues_groupe = LangueSection.objects.filter(groupes=groupe)
            for langue in langues_groupe:
                if not langue in langues:
                    langues.append(langue)
        return langues

    @staticmethod
    def objectList(arg):
        if arg:
            return ForumUser.objects.filter(groupe=arg)
        else:
            return ForumUser.objects.all()

    def send_init_mail(self):
        if self.mail:
            file = open("sent_mails", "w")
            template = get_template("monApp/mail_templates/addUser.txt")
            mail_content = template.render({"username": self.identifiant,
                                            "password": self.password})
            msg = EmailMultiAlternatives("Bienvenue", mail_content, "noreply@docs-ceci-formation.fr", [self.mail])
            msg.send()
            self.password = util.hash(self.password)
            self.save()
            file.write(self.mail)
        else:
            raise Exception("User has no E-mail")

    def send_newpassword(self):
        if self.mail:
            self.password = util.gen_passwd(10)
            template = get_template("monApp/mail_templates/newPassword.txt")
            mail_content = template.render({"username": self.identifiant,
                                            "password":self.password})
            self.password = util.hash(self.password)
            msg = EmailMultiAlternatives('Demande de nouveau mot de passe', mail_content, "noreply@docs-ceci-formation.fr", [self.mail])
            msg.send()
            self.save()
        else:
            raise Exception("User has no e-mail")

class logo(models.Model):
    nom = models.CharField(max_length=50)
    img = models.ImageField(upload_to="static/img/logo")


class Article(models.Model):
    title = models.CharField(max_length=30, null=False)
    subTitle = models.CharField(max_length=100, null=True)
    date = models.DateField(default=timezone.now)
    type_id = models.ForeignKey("ArticleType", on_delete=models.PROTECT, default=1)
    langue = models.ManyToManyField(LangueSection)

    list_template = "monApp/admin_article_list.html"
    form_template = "monApp/admin_article_form.html"

    class Meta:
        verbose_name="article"
        ordering=["date"]

    def __str__(self):
        return self.title

    def get_images_path(self):
        path = "monApp/static/content/%s/"%(self.id)
        try:
            fileList = listdir(path)
            fileList.sort()
            print (fileList)
            return ["content/%s/%s"%(self.id, name) for name in fileList]
        except Exception:
            return []

    def get_audio_path(self):
        path = "monApp/static/content_audio/%s"%(self.id)
        try:
            fileList = listdir(path)
            fileList.sort()
            return ["content_audio/%s/%s"%(self.id, name) for name in fileList]
        except Exception:
            return []

    @staticmethod
    def objectList(arg=None):
        if arg:
            return Article.objects.filter(langue=arg)
        else:
            return Article.objects.all()


class PlannedMail(models.Model):
    to = models.ForeignKey("ForumGroup", on_delete=models.CASCADE)
    subject = models.CharField(null=True, max_length=50)
    content = models.TextField(null=True)
    sent = models.BooleanField(default=False)
    time = models.DateField(default=timezone.now)

    list_template = "monApp/admin_mail_list.html"
    form_template = "monApp/admin_mail_form_test.html"

    @staticmethod
    def objectList(arg=None):
        return PlannedMail.objects.all().order_by("time")

    def __str__(self):
        return "%s - %s - %s/%s/%s" % (self.subject,
                                             self.to,
                                             self.time.day,
                                             self.time.month,
                                             self.time.year,
                                             )

    def send(self):
        for user in self.to.forumuser_set.all():
                txt_content = self.content
                msg = EmailMultiAlternatives(self.subject, txt_content, "noreply@docs-ceci-formation.fr", [user.mail])
                ret = msg.send()
        if ret:
            self.delete()
        else:
            util.report("Erreur d'envoi d'un mail")

class ExamInvite(models.Model):
    to = models.ForeignKey("ForumGroup", on_delete=models.CASCADE)
    date = models.DateTimeField(default=timezone.now)
    examType = models.CharField(default="Toeic", max_length=20)

    list_template = "monApp/admin_exam_list.html"
    form_template = "monApp/admin_exam_form.html"

    def get_nb_accept(self):
        return ExamInviteItem.objects.filter(parent=self.id, accepted=True).count()

    @staticmethod
    def objectList(arg=None):
        return ExamInvite.objects.filter(date__gte=datetime.now()).order_by("date")

    def __str__(self):
        return "%s - %s - %s" % (self.examType, self.to, self.date)

class ExamInviteItem(models.Model):
    user = models.ForeignKey("ForumUser", on_delete=models.CASCADE)
    parent = models.ForeignKey("ExamInvite", on_delete=models.CASCADE)
    accepted = models.BooleanField(default=False)
    link = models.TextField()


    @staticmethod
    def objectList(arg=None):
        return ExamInviteItem.objects.filter(parent=arg)

    def __str__(self):
        return self.user.identifiant

    def send(self):
        template = get_template("monApp/mail_templates/exam_invite.txt")
        text = template.render({"parent": self.parent, "lien": self.link })
        mail = EmailMultiAlternatives("%s du %s"%(self.parent.examType, str(self.parent.date.date())), text, "noreply@docs-ceci-formation.fr", [self.user.mail])
        mail.send()

    def generate_convoc(self):

        doc = Document("monApp/static/toeic.docx")

        doc.paragraphs[0].runs[2].text = self.parent.examType
        doc.paragraphs[1].runs[0].text = self.user.identifiant.replace(".", " ").capitalize()
        date = self.parent.date
        doc.tables[0]._cells[0].paragraphs[1].runs[2].text = date.strftime("%d/%m/%Y")
        doc.tables[0]._cells[0].paragraphs[2].runs[1].text = (date-timedelta(hours=1)).strftime("%Hh%M")
        doc.tables[0]._cells[0].paragraphs[2].runs[6].text = date.strftime("%Hh%M")
        doc.tables[0]._cells[0].paragraphs[2].runs[8].text = "(Durée %s)" % ("1h" if self.parent.examType == "Widaf" else "2h30")


        doc.save("monApp/convocations/%s - %s - %s.docx"%(self.parent.examType, self.user, self.link))
        return("monApp/convocations/%s - %s - %s.docx"%(self.parent.examType, self.user, self.link))

    def send_confirm(self, convoc):
        template = get_template("monApp/mail_templates/exam_confirm.txt")
        text = template.render({"parent": self.parent })
        mail = EmailMultiAlternatives("Confirmation - %s du %s"%(self.parent.examType, str(self.parent.date.date())), text, "noreply@docs-ceci-formation.fr", [self.user.mail])
        mail.attach_file(convoc)
        mail.send()

monApp/forms.py
from django import forms
from monApp import models, util
from django.template.loader import get_template
from django.core.mail import EmailMultiAlternatives
import json
from datetime import datetime, date
from pdf2image import convert_from_bytes
from os import path, mkdir
from Django import settings
import shutil
from hashlib import md5


class LoginForm(forms.Form):
    id = forms.CharField(max_length=50)
    mdp = forms.CharField(max_length=50)


class GroupForm(forms.ModelForm):
    class Meta:
        model = models.ForumGroup
        fields = ("nom", "couleur")

    fichier = forms.ImageField(required=False)

    def save(self, commit=True):
        m = super().save(commit=False)

        if self.cleaned_data["fichier"]:
            new_logo = models.logo.objects.create(nom="logo_%s"%(self.cleaned_data["nom"]))
            new_logo.img = self.cleaned_data["fichier"]
            new_logo.save()
            m.logo = new_logo
        m.save()

class UserForm(forms.ModelForm):
    class Meta:
        model = models.ForumUser
        fields = ("identifiant", "mail", "groupe")
        widgets= {
            'groupe': forms.CheckboxSelectMultiple(),
            'mail': forms.TextInput()
        }

    def save(self, commit=True):
        m = super().save(commit=True)
        if not m.password:
            m.password = util.gen_passwd(10)
            template = get_template("monApp/mail_templates/addUser.txt")
            mail_content = template.render({"username": m.identifiant,
                                            "password": m.password})
            msg=EmailMultiAlternatives("Bienvenue", mail_content, "noreply@docs-ceci-formation.fr", [m.mail])
            msg.send()
            m.password = util.hash(m.password)
        m.save()


class SectionForm(forms.ModelForm):
    class Meta:
        model = models.LangueSection
        fields = ("nom_complet", "nom_apparent", "groupes")
        widgets={
            "groupes": forms.CheckboxSelectMultiple()
        }

class ArticleForm(forms.ModelForm):
    class Meta:
        model=models.Article
        fields=("title", "subTitle", "date", "langue")
        widgets={
            "langue":forms.CheckboxSelectMultiple()
        }
    subTitle = forms.CharField(required=False)
    fichier = forms.FileField(required=False)
    audio = forms.FileField(required=False)

    def save(self, commit=True):
        m = super().save(commit=True)
        if "fichier" in self.files:
            try:
                image_set = convert_from_bytes(self.files["fichier"].file.read())
            except Exception as e:
                self.add_error("fichier", e)
                return 0
            print(path.join(settings.MEDIA_ROOT, "static/content/%s" % (m.id)))
            try:
                shutil.rmtree(path.join(settings.MEDIA_ROOT, "static/content/%s" % (m.id) ))
            except Exception:
                pass
            finally:
                mkdir(path.join(settings.MEDIA_ROOT, "static/content/%s" % (m.id)))

            img_id=0
            for img in image_set:
                img_id += 1
                img.save(path.join(settings.MEDIA_ROOT, "static/content/%s/image_%s.jpg" % (m.id, img_id)))
        if "audio" in self.files:
            if self.files["audio"].name[-4:] != ".mp3":
                self.add_error("audio", "The provided file is not an MP3 file")
                return 0

            try:
                shutil.rmtree(path.join(settings.MEDIA_ROOT, "static/content_audio/%s" % (m.id) ))
            except Exception:
                pass
            finally:
                mkdir(path.join(settings.MEDIA_ROOT, "static/content_audio/%s" % (m.id)))
            with open(path.join(settings.MEDIA_ROOT, "static/content_audio/%s/%s" % (m.id, self.files["audio"].name)), 'wb+') as destination:
                for chunk in self.files["audio"].chunks():
                    destination.write(chunk)



class MailFormTest(forms.ModelForm):

    class Meta:
        model=models.PlannedMail
        fields=("to", "time", "subject", "content")
        widgets={
            "content": forms.Textarea,
        }
        labels={
            "time": "Send date"
        }

class ExcelImportForm(forms.Form):
    file = forms.FileField()


class ChangePasswordForm(forms.Form):
    old_password = forms.CharField(widget=forms.PasswordInput())
    new_password = forms.CharField(widget=forms.PasswordInput())
    new_password_confirm = forms.CharField(widget=forms.PasswordInput())


class ExamResults(forms.Form):
    exam_type = forms.ChoiceField(choices=(("toeic", "Toeic officiel"),
                                           ("widaf","Widaf officiel"),
                                           ('toeic_s5', "Toeic blanc S5"),
                                           ("toeic_s6", "Toeic blanc S6"),
                                           ("widaf_s5", "Widaf blanc S5"),
                                           ("widaf_s6", "Widaf blanc S6")))
    file = forms.FileField()


class ExamInvite(forms.ModelForm):

    class Meta:
        model = models.ExamInvite
        fields=("to", "date", "examType")
        widgets={
            "examType": forms.Select(choices=(("Toeic", "Toeic"), ("Widaf", "Widaf"))),
        }
        labels={"examType":"Exam type"}

    def save(self):
        m = super().save(commit=True)
        for user in m.to.forumuser_set.all():
            hasher = md5()
            string = "%s%s"%(str(m), user.identifiant)
            hasher.update(string.encode("utf-8"))
            hash = hasher.hexdigest()
            item = models.ExamInviteItem.objects.create(user=user, parent=m, link=hash)
            item.save()
            item.send()

monApp/templates/monApp/admin_article_list.html
{% extends "monApp/admin_base.html" %}
{% load static %}
{% block content %}

<article>
    {% for article in objectList %}
        <a href="{% url "admin" model="article" action="edit" arg=article.id %}">
            <div class="article">
                <img src="/static/img/article_icon/doc_F7HUvOg.png" class="art_type"><div class=art_txt>
                    <h1>{{ article.title }}</h1>
                    <h2>{{ article.subTitle }}</h2>
                </div>
                <h3>{{ article.date|date:"Y-m-d" }}</h3>
            </div>
        </a>
    {% endfor %}
</article>
    <a href="{% url "admin" model="article" action="add" %}"><img src={% static "img/add.png" %} class = "admin_add"></a>


{% endblock %}

monApp/templates/monApp/admin_exam_form.html
{% extends "monApp/admin_base.html" %}
{% load static %}
{% block content %}
    <article>
    {% if success %}
        <p class="success">Utilisateur enregistré avec succès!</p>
    {% endif %}
    <form method="POST" enctype="multipart/form-data"/>
    {% csrf_token %}
    <fieldset {% if form.instance.id %}disabled="disabled"{% endif %} style="border: none">
    {{form.as_p}}
    <p>Nombre d'étudiants présents pour le moment: {{ form.instance.get_nb_accept }}</p>
    </fieldset>
    <input type = "submit">
    </form>
    {% if form.instance.id %}
        {% for item in form.instance.examinviteitem_set.all %}
            <div class="mini article" style="display: flex; align-items: center">
            {% if item.accepted %}
            <img src="{% static 'img/ok.png' %}" style="height: 20px;margin: 5px">
            {% else %}
                <img src="{% static 'img/not_ok.png' %}" style="height: 20px;margin: 5px">
            {% endif %}
                    <p>{{ item }}</p>
                </div>
            </div>
        {% endfor %}
    {% endif %}
    </article>
    {% if form.instance.id %}
    <a href="{% url "admin" model="exam_invite" action="delete" arg=form.instance.id %}"><img src="{% static "img/del.png" %}" class = "admin_del"></a>
    {% endif %}
{% endblock %}

monApp/templates/monApp/admin_exam_list.html
{% extends "monApp/admin_base.html" %}
{% load static %}
{% block content %}
    <article>
    {% for exam in objectList %}
        <a href="{% url "admin" model="exam_invite" action="edit" arg=exam.id %}">
            <div class="article">
                    <h1>{{ exam }}</h1>
                </div>
            </div>
        </a>
    {% endfor %}
</article>

    <a href="{% url "admin" action="add" model="exam_invite" %}"><img src={% static "img/add.png" %} class="admin_add"></a>
{% endblock %}

monApp/templates/monApp/admin_excel_import.html
{% extends "monApp/admin_base.html" %}
{% load static %}
{% block content %}
    <article>
        <h1>Importer des utilisateurs depuis un fichier excel</h1>

    <p><a href="/static/downloads/User_import_template.xlsx">Telecharger le template du fichier à remplir</a></p>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
    <br>
        <input type="submit">
    </form>
    </article>

{% endblock %}

monApp/templates/monApp/admin_group_form.html
{% extends "monApp/admin_base.html" %}
{% load static %}
{% block content %}
    <article>
    {% if success %}
        <p class="success">Utilisateur enregistré avec succès!</p>
    {% endif %}
    <form method="POST" enctype="multipart/form-data"/>
    {% csrf_token %}
    {{form.as_p}}
        {% if form.instance %}
            {% if form.instance.logo %}
                <img src="{{ form.instance.logo.img.url }}">
                <br>
            {% endif %}
        {% endif %}
    <input type = "submit">
    </form>
    {% if form.instance.id %}
    <a href = {% url "admin" model="user" action="list" arg=form.instance.id %}>Liste des utilisateurs du groupe</a>
    {% endif %}
    </article>
    {% if form.instance.id %}
    <a href="{% url "admin" model="group" action="delete" arg=form.instance.id %}"><img src="{% static "img/del.png" %}" class = "admin_del"></a>
    {% endif %}
{% endblock %}

monApp/templates/monApp/admin_group_list.html
{% extends "monApp/admin_base.html" %}
{% load static %}
{% block content %}
    <article>
    {% for group in objectList %}
        <a href="{% url "admin" model="group" action="edit" arg=group.id %}">
            <div class="article">
                <img src="{% static 'img/group.png' %}" class="art_type"><div class=art_txt>
                    <h1>{{ group.nom }}</h1>
                </div>
            </div>
        </a>
    {% endfor %}
</article>

    <a href="{% url "admin" action="add" model="group" %}"><img src={% static "img/add.png" %} class = "admin_add"></a>
{% endblock %}

monApp/templates/monApp/admin_section_list.html
{% extends "monApp/admin_base.html" %}
{% load static %}
{% block content %}
    <article>
    {% for section in objectList %}
        <a href="{% url "admin" model="section" action="edit" arg=section.id %}">
            <div class="article">
                <img src="{% static 'img/section.png' %}" class="art_type"><div class=art_txt>
                    <h1>{{ section.nom_complet }}</h1>
                </div>
            </div>
        </a>
    {% endfor %}
</article>

    <a href="{% url "admin" model="section" action="add" %}"><img src={% static "img/add.png" %} class = "admin_add"></a>
{% endblock %}

monApp/templates/monApp/admin_user_form.html
{% extends "monApp/admin_base.html" %}
{% load static %}
{% block content %}
    <article>
    {% if success %}
        <p class="success">Utilisateur enregistré avec succès!</p>
    {% endif %}
    <form method="POST"/>
    {% csrf_token %}
    {{form.as_p}}
    {% if form.instance.mail %}
        <a href="{% url 'newPassword' arg=form.instance.id %}">Réinitialiser le mot de passe</a><br>
    {% endif %}
    <input type = "submit">
    </form>
    </article>
    {% if form.instance.id %}
        <a href="{% url "admin" model="user" action="delete" arg=form.instance.id %}"><img src="{% static "img/del.png" %}" class = "admin_del"></a>
    {% endif %}
{% endblock %}

monApp/templates/monApp/admin_user_list.html
{% extends "monApp/admin_base.html" %}
{% load static %}
{% block content %}
    <article>
    {% for user in objectList %}
        <a href="{% url "admin" model="user" action="edit" arg=user.id %}">
            <div class="mini article">
                    <h1>{{ user.identifiant }}</h1>
                </div>
            </div>
        </a>
    {% endfor %}
</article>

    <a href="{% url "admin" model="user" action="add" %}"><img src={% static "img/add.png" %} class = "admin_add"></a>
{% endblock %}

monApp/templates/monApp/article.html
{% extends 'monApp/base.html' %}
{% load static %}


{% block title %}
{{ article.title }}
{% endblock %}

{% block content %}

<article>
{% if article.get_audio_path %}
<audio controls>
  <source src={% static article.get_audio_path.0 %} type="audio/mpeg">
Your browser does not support the audio element.
</audio>
{% endif %}


{% for image_path in article.get_images_path %}
        <img src="{% static  image_path  %}" class="img_content"/>
{% endfor %}
</article>

{% endblock %}

monApp/templates/monApp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Fjalla+One" rel="stylesheet">

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header style="background:linear-gradient(45deg, {{ user.groupe.all.0.couleur }} 0%,{{ user.groupe.all.0.couleur2 }} 10%)">
        {% if user.groupe.all.0.logo %}
	<img src="{{ user.groupe.all.0.logo.img.url }}" class="main_logo"/>
            <p class = "credits">Créé par Bernard Jénaste - Pôle linguistique</p>
            <div class = "user_info">
            <div class = "l1">
                <p>{{ user.identifiant }}</p>
            <a href="/deco"><img src="{% static 'img/deco.png' %}" class="deco"/></a>
                </div>
                <div class = "l2">
                    <p><a href = "/change_password">Changer de mot de passe</a></p>
                </div>
            </div>
        {% endif %}
	</header>

    <nav>

    </nav>
    <div class="page">
    <aside>
        {% for langue in user.getLangues %}
            <a href="/accueil/langue/{{langue.id}}"><div class="menu">{{ langue.nom_apparent }}</div></a>
        {% endfor %}
    </aside>

{% block content %}
{% endblock %}
    </div>
</body>
</html>

monApp/templates/monApp/change_password.html
{% extends 'monApp/base.html' %}
{% load static %}


{% block title %}
Changement de mot de passe
{% endblock %}

{% block content %}
    <article>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
</form>
    </article>

{% endblock %}

monApp/templates/monApp/forum.html
{% extends 'monApp/base.html' %}

{% block title %}
Fichiers disponibles
{% endblock %}

{% block content %}

<article>
    {% for article in langue.getArticles %}
        <a href="accueil/article/{{ article.id }}">
            <div class="article">
                <img src="/static/img/article_icon/doc_F7HUvOg.png" class="art_type"><div class=art_txt>
                    <h1>{{ article.title }}</h1>
                    <h2>{{ article.subTitle }}</h2>
                </div>
                <h3>{{ article.date|date:"Y-m-d" }}</h3>
            </div>
        </a>
    {% endfor %}

{% if not langue.getArticles %}
<p style="text-align: center;color: gray;">Aucun article disponible dans cette section pour le moment...</p>
{% endif %}
</article>

{% endblock %}

monApp/templates/monApp/home.html
<!DOCTYPE html><html lang="fr">{% load static %}<head>    <meta charset="UTF-8">    <link rel="stylesheet" type="text/css" href="{% static 'css/login_style.css' %}"></style>    <title>Identification</title><head/><body>    <img src="{% static 'img/bg.jpg' %}" class="bg"><section>    <img src="{% static 'img/logo_ecam.jpg' %}" class="logo_id"/>    {% if erreur %}    <p class="erreur">{{ erreur }}</p>    {% endif %}    <p class = "co">Connexion</p>    <form method = "POST">    {% csrf_token %}        <p><label>Identifiant: </label><br>        <input type="text" name="id" value="votre nom" onclick="this.value = '' ">        </p>        <p>        <label>Mot de passe: </label>        <br>        <input type = "password" name = "mdp" value = '.........' onfocus="this.value = '' "/>        </p>        <p><input type = "image" src = "./submit.png" class = "sub"></p>    </form></section></body></html>